-- +goose Up
-- +goose StatementBegin
create table product_variants (
  id bigint primary key generated by default as identity,
  product_id bigint not null references products(id) on delete cascade,
  sku varchar(80) unique,
  title varchar(255) not null,
  description text,
  inserted_at timestamp(0) not null default (now() at time zone 'utc'),
  updated_at timestamp(0) not null default (now() at time zone 'utc')
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table product_variants;
-- +goose StatementEnd
