-- +goose Up
-- +goose StatementBegin
create extension if not exists "citext";

create table products (
  id bigint primary key generated by default as identity,
  parent_id bigint references products(id) on delete set null,
  title varchar(255) not null,
  sku varchar(80) unique,
  slug citext not null unique,
  description text not null,
  base_price decimal(19, 4) not null,
  main_picture text,
  inserted_at timestamp(0) not null default (now() at time zone 'utc'),
  updated_at timestamp(0) not null default (now() at time zone 'utc'),
  check (length(slug) < 255)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table products;
-- +goose StatementEnd
