// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          int64
	Title       string
	Sku         *string
	Slug        string
	Description string
	InsertedAt  pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Picture     *string
}

type ProductVariant struct {
	ID          int64
	ProductID   int64
	Sku         *string
	Title       string
	Description *string
	InsertedAt  pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
