// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Cart struct {
	ID         int64
	InsertedAt pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type CartItem struct {
	ID         int64
	CartID     int64
	ProductID  *int64
	Quantity   decimal.Decimal
	InsertedAt pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Product struct {
	ID            int64
	ParentID      *int64
	TitlePl       string
	TitleEn       *string
	Sku           *string
	Slug          string
	DescriptionPl *string
	DescriptionEn *string
	BasePrice     decimal.Decimal
	MainPicture   *string
	InsertedAt    pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
